# Generated by Django 5.2.11 on 2026-02-07 08:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='active_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
